Prevent override of Salt property on Person update
RHEAGROUP/CDP4-WebServices-Community-Edition pull request #173
Opened 2021-01-14 17:22 UTC by alexatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [x] I have provided test coverage for my change (where applicable)

### Description
Fixes a condition where upon updating a Person without providing a new password could erase the Salt property of that Person, effectively locking them out of the server.

2021-01-14 17:32 UTC, samatrhea approved these changes
that looks very elegant!

2021-01-15 07:51 UTC, lxatrhea requested changes

2021-01-15 07:51 UTC, lxatrhea commented on CDP4Orm/Dao/Supplemental/PersonDao.cs
> +                sqlBuilder.AppendFormat("SELECT * FROM \"{0}\".\"Person_View\"", partition);
In general I think too much data is retrieved. SELECT * could be replaced by SELECT /"ValueTypeSet/".
I also think that it should throw an exception when the Person is null.
It's not about the performance, but more about the expectations of the method (by its name) versus what it really does.

2021-01-15 08:32 UTC, lxatrhea approved these changes

2021-01-15 10:17 UTC, merged