[WIP] Organizational model obfuscation and permission mechanism
RHEAGROUP/CDP4-WebServices-Community-Edition pull request #174
Opened 2021-01-19 19:36 UTC by alexatrhea

### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/RHEAGROUP/CDP4-WebServices-Community-Edition/pulls) open
- [x] I have verified that I am following the CDP4-SDK [code style guidelines](https://raw.githubusercontent.com/RHEAGROUP/CDP4-WebServices-Community-Edition/master/.github/CONTRIBUTING.md)
- [] I have provided test coverage for my change (where applicable)

### Description
Serverside obfuscation of data based on organizational association of the requester.

2021-01-20 07:09 UTC, samatrhea requested changes
code looks very good and super clean, some remarks:
  - think you missed the `Alias` class (next to hyperlink and and definition
  - Nice testable code, but I don't see a unit test for the obfuscation service

2021-01-20 07:09 UTC, samatrhea commented on CDP4WebServices.API/Services/Authorization/ObfuscationService.cs
> +            var citations = resourceResponse.OfType<Citation>().ToList();
i have the impression that the `Alias` dto should be here as well

2021-01-20 07:58 UTC, lxatrhea approved these changes
Looks good.
Somewhat related: Are we sure that Poco's created from these DTO's cannot accidentally be written back to the database? A user's access rights might change during the lifetime of a Session (Cache). Or the user's organizational setting might change.

2021-01-20 07:58 UTC, lxatrhea commented on CDP4-Server.sln.DotSettings
> +   Ahmed Ahmed&#xD;
Most of us are using his complete name in headers: Ahmed Abulwafa Ahmed

2021-01-20 08:36 UTC, alexatrhea commented
> Looks good.
> Somewhat related: Are we sure that Poco's created from these DTO's cannot accidentally be written back to the database? A user's access rights might change during the lifetime of a Session (Cache). Or the user's organizational setting might change.

This is in progress

2021-01-22 22:24 UTC, alexatrhea commented
Handed over to @lxatrhea for unit test fixing and finalization

2021-01-28 16:37 UTC, merged